### ISSUE TITLE
Bug: Crash with Mob Rebirth-1.12.2

### ISSUE THREAD

**Issue by Snapshotlight** [Chumbanotz/MutantBeasts#12]
I was using Mob Rebirth. However, when I killed a Mutant Zombie, the game crashed. 
I wonder if this can be fixed, Sorry that I cannot provide the crash report because this crash happened long ago (and I was using old version at that time.)

**Comment by Snapshotlight** [comment]
uhh, the exact time may be January or February this year.

**Comment by Chumbanotz** [comment]
Which version of Mob Rebirth? I tried it with the latest 1.12.2 version of Mob Rebirth, and I did not get a crash.
