### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by WenXin20** [Chumbanotz/MutantBeasts#14]
Minecraft v1.15.2
Forge v31.1.74
Mutant Beasts v1.0.6

The game errors during the game load.

[Crash Log](https://gist.github.com/WenXin20/6a64a308652e0bba07c926add8416f91) Error starts at `[23:29:08]`.
![2020-05-11_23 59 02](https://user-images.githubusercontent.com/12000593/81640764-03df9680-93e5-11ea-9309-f053fd5282d6.png)

**Comment by Chumbanotz** [comment]
Just released a fix. Let me know if it works: [https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/files](https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/files)

**Comment by WenXin20** [comment]
Yes, that fixed it, thanks!
