### ISSUE TITLE
1.16.1 - biomeWhitelist keeps resetting to default

### ISSUE THREAD

**Issue by bessiq** [Chumbanotz/MutantBeasts#19]
Hey, thanks for porting this to 1.16! It's working well, except whenever I add other mod IDs to the biomeWhitelist, it always reverts to `biomeWhitelist = ["minecraft"]` when I launch the game again. I've tried a few variations, like so:

`biomeWhitelist = ["biomesoplenty"]`
`biomeWhitelist = ["minecraft", "biomesoplenty", "byg"]`

I thought maybe I got the syntax wrong when I added multiple mod IDs, but it still resets if just replacing "minecraft". The spawn weight settings don't reset, though.

A couple other mods I've used in 1.16 also had this issue, where just the biome configs would reset. They did end up getting it resolved, but I'm not sure how. ([Earth2Java](https://github.com/Slexom/earth2java) was one of them, fwiw.)

Anyway, hopefully I can see these monstrous beasts in modded biomes soon. Thanks!

**Comment by Chumbanotz** [comment]
Should be fixed as of version 1.1.1.

**Comment by bessiq** [comment]
Yep, it's working in the new update. Thanks!
