### ISSUE TITLE
[1.16.3] Mobs don't utitlize BiomeDictionary to spawn

### ISSUE THREAD

**Issue by BugmanBugman** [Chumbanotz/MutantBeasts#24]
Title. Mobs only spawn in vanilla biomes as of right now, and don't spawn in any modded biomes.

**Comment by Chumbanotz** [comment]
I changed the spawning so that, by default, the mutants only spawn in vanilla biomes. You can change this by editing the config and putting the ID of the mod you would like for the mutants to spawn in the biome whitelist.
