### ISSUE TITLE
Random crash 

### ISSUE THREAD

**Issue by runescapejon** [Chumbanotz/MutantBeasts#3]
https://pastebin.com/raw/Li0bQ1nf
I have no idea how to reproduce... and have no other information 
feel free to close it if just not enough info

**Comment by Chumbanotz** [comment]
There is actually enough information, thanks for posting the crash report.

**Comment by runescapejon** [comment]
Cool! will the fix be on 1.12.2 ?

**Comment by Chumbanotz** [comment]
Yes, soon.
