### ISSUE TITLE
Crash: ClientPlayerEntity should not be used on a dedicated server.

### ISSUE THREAD

**Issue by Vaelzan** [Chumbanotz/MutantBeasts#4]
See this line:

https://github.com/Chumbanotz/MutantBeasts/blob/21c69708f07ff722b6203bbeb51948911693e059/src/main/java/chumbanotz/mutantbeasts/EventHandler.java#L105

This will crash any dedicated server as soon as the player is hurt as you are calling client-side code.

**Comment by Chumbanotz** [comment]
I've already realized that would be an issue, but thanks for the report anyway.
