### ISSUE TITLE
null error with one probe mod 

### ISSUE THREAD

**Issue by runescapejon** [Chumbanotz/MutantBeasts#6]
When you have one probe mod installed with Mutant beast installed and then kill an mutant creeper, let that spawn the egg place down then look at that entity egg then you'll crash

https://pastebin.com/raw/tqVU2nLZ

version i am on is `theoneprobe-1.12-1.4.28.` and `MutantBeasts-1.12.2-0.6.2`

**Comment by Chumbanotz** [comment]
Should be fixed for [0.6.3](https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/files/2888619)

**Comment by runescapejon** [comment]
thank you it work! <3
