### ISSUE TITLE
[Crash] NullPointerException caused by Endersoul Fragment ticking.

### ISSUE THREAD

**Issue by Vaelzan** [Chumbanotz/MutantBeasts#8]
https://github.com/Chumbanotz/MutantBeasts/blob/8aed1e17852d04dc6c6f1c595b0e27315f07f1b3/src/main/java/chumbanotz/mutantbeasts/entity/EndersoulFragmentEntity.java#L123

The referenced line of code above can cause a crash as directly above it you potentially set this.collector to be null, causing an immediate NullPointerException as it tries to use this.collector as a parameter to getDistanceSq directly afterwards.

See: https://pastebin.com/qSytUy7h for an example of the crash.

**Comment by Chumbanotz** [comment]
Fixed.
